// Generated by CoffeeScript 1.10.0
(function() {
  var activateIframe, appendToCache, baseURL, cacheSize_forward, containsPageNumber, getPageNumber, goNext, goPrev, inCache, isA6A5A1X2COMBO, isFlashPage, isHomestuckUrl, makeIframe, makeUrl, nextUrl, pad6, prependToCache, prevUrl, removeFromCache, scroll, scrollAmount, sendMessageToIframe, setHash, update, updateFromHash,
    indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  cacheSize_forward = 4;

  baseURL = 'http://www.mspaintadventures.com/';

  pad6 = function(pageNum) {
    var pad, str;
    pad = '000000';
    str = '' + pageNum;
    return pad.substring(0, pad.length - str.length) + str;
  };

  isA6A5A1X2COMBO = function(pageNum) {
    return (7688 <= pageNum && pageNum <= 7824);
  };

  makeUrl = function(pageNum) {
    var php;
    if (pageNum === 1900) {
      pageNum = 1901;
    }
    php = '';
    if (pageNum === 7680) {
      return 'http://www.mspaintadventures.com/007680/007680.html';
    } else if (pageNum === 6009) {
      php = 'cascade.php';
    } else if (pageNum === 5982) {
      php = 'sbahj.php';
    } else if ((5664 <= pageNum && pageNum <= 5981)) {
      php = 'scratch.php';
    } else if ((8375 <= pageNum && pageNum <= 8430)) {
      php = 'ACT6ACT6.php';
    } else if ((7614 <= pageNum && pageNum <= 7677)) {
      php = 'trickster.php';
    } else if (isA6A5A1X2COMBO(pageNum)) {
      php = 'ACT6ACT5ACT1x2COMBO.php';
    }
    return baseURL + php + '?s=6&p=' + pad6(pageNum);
  };

  containsPageNumber = function(url) {
    if (url.startsWith('http://www.mspaintadventures.com/007680/')) {
      return true;
    }
    return /p=(\d+)/.exec(url).length > 0;
  };

  getPageNumber = function(url) {
    if (url.startsWith('http://www.mspaintadventures.com/007680/')) {
      return 7680;
    }
    return parseInt(/p=(\d+)/.exec(url)[1]);
  };

  nextUrl = function(url) {
    var pageNum;
    pageNum = getPageNumber(url);
    if (isA6A5A1X2COMBO(pageNum)) {
      pageNum += 2;
    } else {
      pageNum += 1;
    }
    return makeUrl(pageNum);
  };

  prevUrl = function(url) {
    var pageNum;
    pageNum = getPageNumber(url);
    if (isA6A5A1X2COMBO(pageNum)) {
      pageNum -= 2;
    } else {
      pageNum -= 1;
    }
    return makeUrl(pageNum);
  };

  window.currentUrl = function() {
    return $('#current-page').attr('src');
  };

  window.getIframeUnsafe = function(url) {
    return $(".stuckpage[src=\"" + url + "\"]");
  };

  window.getIframe = function(url) {
    var iframe;
    iframe = getIframeUnsafe(url);
    console.assert(iframe.length === 1);
    return iframe;
  };

  inCache = function(url) {
    var numIframes;
    numIframes = getIframeUnsafe(url).length;
    console.assert((0 <= numIframes && numIframes <= 1));
    return numIframes > 0;
  };

  makeIframe = function(url) {
    return "<iframe class=\"stuckpage\" contentHeight=\"5\" src=\"" + url + "\"></iframe>";
  };

  sendMessageToIframe = function(url) {
    var message;
    message = {
      'messagetype': 'your iframeSrc is',
      'iframeSrc': url
    };
    return getIframe(url)[0].contentWindow.postMessage(message, '*');
  };

  activateIframe = function(url) {
    var iframe;
    iframe = getIframe(url);
    return iframe.load(function() {
      return setTimeout(sendMessageToIframe, 0, url);
    });
  };

  window.onmessage = function(event) {
    var data;
    data = event.data;
    if (data.page !== data.iframeSrc) {
      if (isHomestuckUrl(data.page)) {
        removeFromCache(data.iframeSrc);
        update(data.page);
      }
    }
    if (data.contentHeight) {
      return getIframe(data.page).attr('contentHeight', data.contentHeight);
    }
  };

  prependToCache = function(url) {
    $('#cache-pages').prepend(makeIframe(url));
    return activateIframe(url);
  };

  appendToCache = function(url) {
    $('#cache-pages').append(makeIframe(url));
    return activateIframe(url);
  };

  removeFromCache = function(url) {
    return getIframe(url).remove();
  };

  isHomestuckUrl = function(url) {
    return url.startsWith(baseURL) && containsPageNumber(url);
  };

  scroll = function(topOrNot) {
    $("html, body").stop();
    if (topOrNot != null) {
      return $(window).scrollTop(topOrNot);
    } else {
      return $(window).scrollTop();
    }
  };

  isFlashPage = function(url) {
    if (!containsPageNumber(url)) {
      return true;
    }
    return pad6(getPageNumber(url)) in window.flashPages;
  };

  update = function(targetUrl) {
    var i, j, k, l, len, ref, ref1, url, urlsToCache;
    console.assert(isHomestuckUrl(targetUrl));
    urlsToCache = [targetUrl];
    url = targetUrl;
    for (i = j = 0, ref = cacheSize_forward; 0 <= ref ? j <= ref : j >= ref; i = 0 <= ref ? ++j : --j) {
      url = nextUrl(url);
      urlsToCache.push(url);
    }
    for (i = k = ref1 = urlsToCache.length - 1; k >= 0; i = k += -1) {
      url = urlsToCache[i];
      if ((!inCache(url)) && inCache(nextUrl(url)) && !isFlashPage(url)) {
        prependToCache(url);
      }
    }
    if (isFlashPage(url)) {
      prependToCache(targetUrl);
    }
    for (l = 0, len = urlsToCache.length; l < len; l++) {
      url = urlsToCache[l];
      if ((!inCache(url)) && !isFlashPage(url)) {
        appendToCache(url);
      }
    }
    $('#current-page').removeAttr('id');
    getIframe(targetUrl).attr('id', 'current-page');
    if (targetUrl.startsWith('http://www.mspaintadventures.com/?s=6&p=')) {
      scroll(29);
    } else {
      scroll(0);
    }
    $('#hold-your-horses').detach().insertAfter(getIframe(targetUrl));
    $('.stuckpage').each(function() {
      url = $(this).attr('src');
      if (indexOf.call(urlsToCache, url) < 0 || (isFlashPage(url) && url !== targetUrl)) {
        return removeFromCache(url);
      }
    });
    document.title = 'ReadHomestuck #' + getPageNumber(targetUrl);
    setHash(targetUrl);
    return console.assert(inCache(currentUrl()));
  };

  scrollAmount = function() {
    return 0.6 * window.innerHeight - 20;
  };

  goNext = function() {
    var contentBottom;
    contentBottom = parseInt(getIframe(currentUrl()).attr('contentHeight')) + 20;
    if (scroll() + $(window).height() > contentBottom) {
      return update(nextUrl(currentUrl()));
    } else {
      $("html, body").animate({
        scrollTop: Math.min(contentBottom + 10 - $(window).height(), scroll() + scrollAmount())
      });
      return setHash(currentUrl());
    }
  };

  goPrev = function() {
    if (scroll() <= 30) {
      return update(prevUrl(currentUrl()));
    } else {
      $("html, body").animate({
        scrollTop: scroll() - scrollAmount()
      });
      return setHash(currentUrl());
    }
  };

  setHash = function(hash) {
    return history.pushState({}, 'MORE HOMESTUCK', '#' + hash);
  };

  updateFromHash = function(hash) {
    if (hash.startsWith('#' + baseURL)) {
      return update(document.location.hash.substring(1));
    } else if (hash.startsWith('#next')) {
      return goNext();
    } else if (hash.startsWith('#prev')) {
      return goPrev();
    } else {
      return update('http://www.mspaintadventures.com/?s=6&p=001901');
    }
  };

  window.onpopstate = function(event) {
    return updateFromHash(document.location.hash);
  };

  $('body').mousedown(function(event) {
    var target;
    if (event.which !== 1) {
      return;
    }
    target = $(event.target);
    if (target.is('body>center') || target.is('body')) {
      event.preventDefault();
      if (event.pageX < $(window).width() / 2) {
        return goPrev();
      } else {
        return goNext();
      }
    }
  });

  updateFromHash(document.location.hash);

}).call(this);

//# sourceMappingURL=main.js.map
